# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4363a4af4dc82957f201fa8b6e664d8be1fc864c71107dab3887ab1654a4c15338a08384a7603a53abe7d0bdb400b8f663c0ab36924d646de09320c9c846fde

test:
  secret_key_base: e1ac42a4f271af55c00bc2445f3815feaeaac8731c20c1e67e31483608910a87b6369d6d9230870ff8728fa1281edddd796c02e3c08f88352c0933ebecce9749

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
